"""Added priority to Task

Revision ID: 949fbeb36852
Revises: 828a35e6c552
Create Date: 2025-07-10 16:58:51.897347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "949fbeb36852"
down_revision: Union[str, Sequence[str], None] = "828a35e6c552"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_priority = sa.Enum("low", "medium", "high", name="task_priority")
    task_priority.create(op.get_bind())
    op.add_column(
        "tasks",
        sa.Column("priority", task_priority, nullable=False, server_default="medium"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "priority")
    sa.Enum(name="task_priority").drop(op.get_bind())

    # ### end Alembic commands ###
